plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ellesjourney.tracker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ellesjourney.tracker'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
